language: cpp
os:
  - linux
  - osx

compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
      - cmake
      - make
      - pkg-config
      - libmicrohttpd-dev
      - libxml2-dev
      - libleveldb-dev
      - libsnappy-dev
      - libjson0-dev
      - libhtmlcxx-dev
      - libicu-dev
      - libcurl4-gnutls-dev
      - netcat
      - curl
  homebrew:
    packages:
      - make
      - cmake
      - pkg-config
      - libmicrohttpd
      - libxml2
      - leveldb
      - snappy
      - json-c
      - htmlcxx
      - icu4c
      - gnutls
      - netcat
      - curl
    update: true

script:
 - make
 - make test
