env:

before_install: 
 - lsb_release -a
 - sudo apt-get update
install:
 - sudo apt-get install cmake
 - sudo apt-get install make
 - sudo apt-get install pkg-config
 - sudo apt-get install libmicrohttpd-dev
 - sudo apt-get install libxml2-dev
 - sudo apt-get install libleveldb-dev
 - sudo apt-get install libsnappy-dev
 - sudo apt-get install libjson0-dev
 - sudo apt-get install libhtmlcxx-dev
 - sudo apt-get install libicu-dev
 - sudo apt-get install libcurl4-*-dev
 - sudo apt-get install netcat
 - sudo apt-get install curl

language: cpp
compiler:
 - gcc
 - clang
script:
 - make
 - make test
